language: node_js
node_js:
- '5'
script:
- npm run build
deploy:
  provider: s3
  region: us-west-2
  access_key_id:
    secure: "llFk6m2X5Ppt1XuWKJMPXv9lKhHgQmhIoZyolU9rCS/Pm5R12DPF/dkvjm6GY10ZYjmDlKvyMxI7ChbnWlndWOT2NtZ2px2WNAp5HsQ1JI8dm/m/UccALLXiU9LEs4f9qPFqWYCtroG9uRLHN69aAOkq3jGVewKMzFIyHjlpakAmGwAewV1FAd4lccpH5ORHolNW8R7bt1Xi57kqmSrLeNSbIXUgU7O5FA/4O2x+T5EyQRqOiRYrr66G8OAmoSXl6opwrdl3DjzLFQRPHGOJMQsIvmc2B9fyvuQDot8zjbfYx6qoOWX8b99N9stpNRqpoGr1bDdbznuH1zrgL86DcC6UJpPZAgQWZCm2f9ZmEaiCPhf94GnFaK/r3bDVGb7gVrqdMJFBq5V5uVUwf+cVy4zc7B+FTpXnSycMtVRAGeBF0OBwEKtdpn84L8W9QNuDqFcwDw3vhfqwxo4cOVlE9kfOyBVigkn5NQZ7MbKrb2STx+x5gSOtjZ0OZDHbb5DuKRkg50TKuUVlZjRmYXo01XJGYapLkh5DDtWjZKcvMPkXS/wyZDOx29jCH3UCzyiVZhq68khNvCVLsIlTzCFhr3f/7K3i9mPMDn6Kbr7+/tEVoSAfnLspj1fsXbquqdWjUu+lHD7wUNRC1WLexpv9npKtlkx3Q95bUhF/xQYkJiI="
  secret_access_key:
    secure: "PrtLFSjEKm16fKChSLTrkG31tm+vKw3aLJjsiKTox8wBtG1xc383nkAd5JpTEq6TwjZR9vozHwHIvrCFfgZ4swse4rEfJlwc7rFtO3e1WYD/ffR6KEv3AGuwWq4kpnvvVe9QckxSSpcnQ/C+Da0Oxzpfh0/gmug2gfOjqNLs4fXUmmkxDPVdHk9yiuwolMoP3AMWVEIWc7P5GR9c9AZuenSTlxbACg+GgfhDTphuPw67A34EVVtcVkYNylsMaee7Ck63jTqadObaHCxWFc7GGayg9tRjmNFrQB0V+BsHVzdHMN0ZhTbY3bEmR4NzLdw4/TIraORjLeM+/BPlXcRqo1i0/6R2QcGWjXNNekxOGOzndbosZiPk597ML7PKrkzpwTjnINP04HiU/3lfHtzYX4RGbvl0ud55uh/+mwtHZHSGaG2cpFJmqImQlaKuLgR/TH/sp2MwQ3VjWj/t80jHSq5Yt3kYJCRJVIgOpb0F4AO6rXfGiXhI4KuKd7bMMBdkf9elITP5lhRJ2HSWoLfx2hT+o3jGsm+DcIxnbpd2ULZ3ffiikGzK0b6Im+Aqi/eMrzu0mpZcYS1ydHxgyng2PiyyzdgSTx2TPxHVYOEpqVzTOYQxGTf/7/+WlQ2mlTbi6ydoMmAsDKWVoevU8RsfS9GC0OYL1rw6VKOHWP9Eeek="
  bucket: ted.pennin.gs
  local-dir: dist
  skip_cleanup: true
  acl: public_read
  on:
    repo: tedpennings/site
