[build]
command = "yarn build"
publish = "dist"

[build.environment]
TERM = "xterm"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
  Document-Policy = "js-profiling"
