version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:10

commands:
  build_assets:
    steps:
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Build assets
          command: yarn build
  cache_dependencies:
    steps:
      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - build_assets
      - cache_dependencies

  deploy:
    <<: *defaults
    steps:
      - checkout
      - build_assets
      - run:
          name: Upload assets
          command: yarn upload

workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore: main
      - deploy:
          filters:
            branches:
              only: main
