version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:12

commands:
  build_assets:
    steps:

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Build assets
          command: yarn build
      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

workflows:
  build_and_test:
    jobs:
      - build
