version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:12

commands:
  build_assets:
    steps:
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build assets
          command: yarn build
  cache_dependencies:
    steps:
      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - build_assets
      - cache_dependencies

  deploy:
    <<: *defaults
    steps:
      - checkout
      - build_assets
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: build
          overwrite: true
          to: "s3://ted.pennin.gs"

workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore: main
      - deploy:
          filters:
            branches:
              only: main

orbs:
  aws-s3: circleci/aws-s3@1.0.16
