version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:12

commands:
  build_assets:
    steps:
      - run:
          name: Build assets
          command: yarn && yarn build

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - build_assets

  deploy:
    <<: *defaults
    steps:
      - build_assets
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: build
          overwrite: true
          to: "s3://ted.pennin.gs"

workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore: main
      - deploy:
          filters:
            branches:
              only: main

orbs:
  aws-s3: circleci/aws-s3@1.0.16
