version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Build assets
          command: yarn && yarn build
      - save_cache:
          key: assets-{{ .BuildNum }}
          paths:
            - build

  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - restore_cache:
          keys:
            - assets-{{ .BuildNum }}
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: build
          overwrite: true
          to: "s3://ted.pennin.gs"

workflows:
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
orbs:
  aws-s3: circleci/aws-s3@1.0.16
