version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          command: yarn && yarn build
  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          command: yarn && yarn build
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: buil
          overwrite: true
          to: "s3://ted.pennin.gs"

workflows:
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
orbs:
  aws-s3: circleci/aws-s3@1.0.16
