jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: yarn && yarn build
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: buil
          overwrite: true
          to: "s3://ted.pennin.gs"
orbs:
  aws-s3: circleci/aws-s3@x.y

version: 2.1
