name: Lint and Build

on: push

jobs:
  lint_and_build:
    name: Lint and Build
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env:
      YARN_CACHE_FOLDER: .yarn-cache

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      # Cache is shared with Cypress workflow
      - uses: actions/cache@v2
        name: yarn cache
        with:
          path: .yarn-cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Build Assets
        run: yarn build
