name: Build and Lint

on: push

jobs:
  build_and_lint:
    name: Build and Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run Lint
        run: yarn lint
      - name: Build
        run: yarn build
