name: Lint and Build

on: push

jobs:
  lint_and_build:
    name: Lint and Build
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env:
      YARN_CACHE_FOLDER: .yarn-cache

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        name: Restore yarn cache
        with:
          path: .yarn-cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn Install
        run: yarn install --frozen-lockfile

      - name: Run Lint
        run: yarn lint

      - name: Build Assets
        run: yarn build
