name: Cypress
on: pull_request
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      # Cache is shared with Build and Lint workflow
      - uses: actions/cache@v2
        name: yarn cache
        with:
          path: .yarn-cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: Wait for Netlify
        uses: probablyup/wait-for-netlify-action@3.2.0
        id: waitForDeployment
        with:
          site_id: 3c91e3a5-7afd-49b3-82a0-142dfc07929e
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}

      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          record: true
          config: baseUrl=${{ steps.waitForDeployment.outputs.url }}
          browser: chrome
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # this is automatically set by GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: test
