name: Cypress
on: pull_request
jobs:
  integration:
    runs-on: ubuntu-latest

    jobs:
    cypress:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        # Cache is shared with Build and Lint workflow
        - uses: actions/cache@v2
          name: yarn cache
          with:
            path: .yarn-cache
            key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

        - name: yarn install
          run: yarn install --frozen-lockfile

        - name: Wait for Netlify
          uses: probablyup/wait-for-netlify-action@3.2.0
          id: waitForDeployment
          with:
            site_id: kind-pike-1cc745
          env:
            NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}

        - name: Run Cypress
          uses: cypress-io/github-action@v2
          with:
            record: true
            config: baseUrl=${{ steps.waitForDeployment.outputs.url }}
          env:
            # pass the Dashboard record key as an environment variable
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            # this is automatically set by GitHub
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
