name: Cypress
on: pull_request
jobs:
  cypress:
    runs-on: ubuntu-latest
    container: cypress/included:5.1.0
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Wait for Netlify
        uses: probablyup/wait-for-netlify-action@3.2.0
        id: waitForDeployment
        with:
          site_id: 3c91e3a5-7afd-49b3-82a0-142dfc07929e
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}

      - name: Run Cypress
        run: cypress run --record --config baseUrl=${{ steps.waitForDeployment.outputs.url }} --browser chrome --group default
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          NODE_ENV: test
